name: diffcheck result

on:
    push
    
jobs:
    build_and_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: g++ -std=c++17 -Wall *.cpp -o battle
            - run: ./outcheck.sh battle battle_expected.txt
            - uses: actions/upload-artifact@v2
              with:
                name: Diffresult Artifact
                path: output.txt