name: doxygen generate

on:
  push:
    branches:	
      - attackspeed
      - gh-pages

jobs:
    generate_documentation:
        name: generate and artifact doxygen docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - run: sudo apt-get install doxygen
            - run: sudo apt-get install graphviz
            - run: doxygen doxygenconfig

            - name: Upload docxygen documents
              uses: s0/git-publish-subdir-action@v2.4.0

              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: docs/html
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}