name: doxygen generate

on:
  push:
    branches:
      - attackspeed
      - gh-pages

    
jobs:
    generate_and_deploy_documentation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@attackspeed
            - name: install and run doxygen + graphviz
            - run: sudo apt-get install doxygen
            - run: sudo apt-get install graphviz
            - run: doxygen doxygenconfig


            name: push to gh-paged
            uses: s0/git-publish-subdir-action@v2.4.0
            env:
              REPO: self
              BRANCH: gh-pages
              FOLDER: docs/html
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
