name: jparser test

on:
    push
    
jobs:
    jparsetest:
        runs-on: ubuntu-latest
        container: luczadennis/mosze:latest
        steps:
            - uses: actions/checkout@v2
            - run: ./jparsetest.sh