name: Analysis/Memtest

on:
    push
    
jobs:
    build_and_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install valgrind
            - run: sudo apt install clang
            - run: sudo apt install cppcheck
            - run: clang++ *.cpp -o battle -Wall -Wextra -Werror
            - run: cppcheck *.cpp --enable=warning --error-exitcode=1 --output-file=cppcheckartifact.txt
	    - name: Upload artifact
	      uses: actions/upload-artifact@v2
	      with:
		 name: cppcheckartifact
		 path: ./cppcheckartifact.txt
            - run: valgrind --track-origins=yes --error-exitcode=1 --leak-check=full ./battle Units/a.txt Units/b.txt