name: Analysis/Memtest

on:
    push
    
jobs:
    build_and_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install valgrind
            - run: sudo apt install cppcheck
            - name: Build
              run: make build

            - name: Running code analysis
              run: make checkcppout
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                 name: cppcheckartifact
                 path: ./cppcheckartifact.txt

            - name Code analysis
              run: make analysis

            - name: Running memtest
              run: make memtest

            - run: ./outcheck.sh battle scenario1.json output1.txt
            - run: ./outcheck.sh battle scenario2.json output2.txt