name: Analysis/Memtest

on:
    push
    
jobs:
    build_and_check:
        runs-on: ubuntu-latest
        container: luczadennis/mosze:latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: make build

            - name: Running code analysis
              run: make checkcppout
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                 name: cppcheckartifact
                 path: ./cppcheckartifact.txt

            - name: Code analysis
              run: make analysis

            - name: Running memtest
              run: make memtest