name: Analysis/Memtest

on:
    push
    
jobs:
    build_and_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install valgrind
            - run: sudo apt install clang
            - run: sudo apt install cppcheck
            - run: clang++ *.cpp -o battle -Wall -Wextra 
            - run: cppcheck *.cpp --enable=warning
            - run: valgrind --track-origins=yes ./battle
